// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSi7TnCEx2wBxUS922aAJbmqTkpM7UlZc',
    appId: '1:657680219795:web:5e922f46bd98e2fcc65766',
    messagingSenderId: '657680219795',
    projectId: 'xtrip-ios',
    authDomain: 'xtrip-ios.firebaseapp.com',
    storageBucket: 'xtrip-ios.appspot.com',
    measurementId: 'G-CYJ2K6MZ8B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcq61EHvUCAH0bWfxvq9jz-2sXvPyI9nk',
    appId: '1:657680219795:android:174e408475e0510ac65766',
    messagingSenderId: '657680219795',
    projectId: 'xtrip-ios',
    storageBucket: 'xtrip-ios.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCEM2KTt69yDQ16mijiyO4zg_UTTa1y5U',
    appId: '1:657680219795:ios:8171a1c659a50957c65766',
    messagingSenderId: '657680219795',
    projectId: 'xtrip-ios',
    storageBucket: 'xtrip-ios.appspot.com',
    iosClientId: '657680219795-gdml719s07ubftgenbjru6qs47qfqdog.apps.googleusercontent.com',
    iosBundleId: 'com.atastay.xtripMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCEM2KTt69yDQ16mijiyO4zg_UTTa1y5U',
    appId: '1:657680219795:ios:8171a1c659a50957c65766',
    messagingSenderId: '657680219795',
    projectId: 'xtrip-ios',
    storageBucket: 'xtrip-ios.appspot.com',
    iosClientId: '657680219795-gdml719s07ubftgenbjru6qs47qfqdog.apps.googleusercontent.com',
    iosBundleId: 'com.atastay.xtripMobile',
  );
}
